### ISSUE TITLE
Tabs holywar

### ISSUE THREAD

**Issue by tmshv** [Massugunaen/SUAI_JS#1]
Please don't use tab. Setup your vim to use 4 spaces. Thanks.

**Comment by Massugunaen** [comment]
Programming in sublime now :/

**Comment by tmshv** [comment]
This piece of software also support 4 space indentation.

**Comment by Massugunaen** [comment]
Why should I change it?
Is this some kind of basis stuff?

**Comment by tmshv** [comment]
This is holy war. Use 4 spaces and shut up.

**Comment by Massugunaen** [comment]
stop bullying, man, I'm trying hard

**Comment by tmshv** [comment]
Relax, I'm just kidding you. Tabs awesome.
